#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Monitors
if [[ $(xrandr -q | grep 'DP-0 connected') ]]; then
        xrandr --output DP-0 --primary --mode 2560x1440 --rate 165 --rotate normal --output HDMI-0 --right-of DP-0 --mode 1920x1080 --rate 100 --rotate right
fi

# Workspaces
bspc monitor DP-0 -d 1 2 3 4 5 6 7 8
bspc monitor HDMI-0 -d 9

bspc config focus_follows_pointer true
xsetroot -cursor_name left_ptr

# Rules
bspc rule -a firefox center=true state=tiled desktop='^1' &
bspc rule -a Alacritty state=tiled desktop='^2' &
bspc rule -a Mullvad\ Browser center=true state=tiled desktop='^3' &
bspc rule -a TelegramDesktop state=tiled desktop='^4' &
bspc rule -a heroic state=tiled desktop='^5' &
bspc rule -a awakened-poe-trade manage=off

# Window borders
bspc config border_width 3
bspc config window_gap 15

bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config paddingless_monocle true

#AutoStart aplications
~/.config/bspwm/launch.sh